"""Frontend tests for the contribute page.

Tests artifact contribution form, validation, and submission functionality.
"""

import pytest
import time
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC

# --- Configuration ---
# NOTE: Update TARGET_URL to point to your contribution page
# If running locally: TARGET_CONTRIBUTE_URL = "http://localhost:8080/contribute.html"
TARGET_CONTRIBUTE_URL = "https://dkc81a64i5ewt.cloudfront.net/contribute.html"

# Define a short timeout for API interaction waits
API_TIMEOUT_SECONDS = 10 

# Define mock inputs for the test
MOCK_URL = "https://huggingface.co/deepseek-ai/DeepSeek-V3.2"
MOCK_TYPE = "model" # Must be one of 'model', 'dataset', or 'code'

# --- Test Cases ---

def test_contribute_page_elements_present(driver):
    """
    Test 1: Check that the required form elements are present and the initial state is correct.
    """
    driver.get(TARGET_CONTRIBUTE_URL)
    wait = WebDriverWait(driver, 5)

    # 1. Check title
    assert "Contribute" in driver.title
    
    # 2. Check form title/subtitle
    assert driver.find_element(By.CLASS_NAME, "contribution-title").is_displayed()
    
    # 3. Check input fields and selectors
    url_input = wait.until(EC.visibility_of_element_located((By.ID, "artifactUrl")))
    type_select = driver.find_element(By.ID, "artifactType")
    submit_button = driver.find_element(By.ID, "submitButton")
    
    assert url_input.is_displayed()
    assert type_select.is_displayed()
    assert submit_button.is_displayed()

    # 4. Check initial button text
    assert "Submit Artifact" in submit_button.text


def test_contribute_client_side_validation(driver):
    """
    Test 2: Verify the form cannot be submitted without required fields (client-side 'required' attribute).
    """
    driver.get(TARGET_CONTRIBUTE_URL)
    wait = WebDriverWait(driver, 5)
    
    url_input = wait.until(EC.visibility_of_element_located((By.ID, "artifactUrl")))
    submit_button = driver.find_element(By.ID, "submitButton")

    # 1. Attempt to click submit without filling anything
    submit_button.click()
    
    # 2. The URL input has the 'required' attribute, so the browser should prevent the submission
    # We assert that the message container is still hidden (no error message generated by JS yet)
    message_container = driver.find_element(By.ID, "messageContainer")
    assert "hidden" in message_container.get_attribute("class"), \
        "Message container appeared, suggesting client-side validation failed."
    